######################################################################
# Automatically generated by qmake (2.01a) ?? ???. 24 01:51:02 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
OBJECTS_DIR = obj
DESTDIR = bin

# Input
HEADERS += form.h matrix.h qmatrixview.h
SOURCES += form.cpp main.cpp matrix.cpp qmatrixview.cpp
RESOURCES += resources/resources.qrc
